// @flow
export const START_FETCH_ALL_CATS = 'FETCH_ALL_CATS';
export const RECEIVE_ALL_CATS = 'RECEIVE_ALL_CATS';

export const START_FETCH_ALL_DOGS = 'FETCH_ALL_DOGS';
export const RECEIVE_ALL_DOGS = 'RECEIVE_ALL_DOGS';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
