export const START_FETCH_ALL_CATS = "FETCH_ALL_CATS";
export const RECEIVE_ALL_CATS = "RECEIVE_ALL_CATS";

export const START_FETCH_ALL_DOGS = "FETCH_ALL_DOGS";
export const RECEIVE_ALL_DOGS = "RECEIVE_ALL_DOGS";

export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";